spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin





server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${EUREKA_CLIENT_INSTANCE_HOSTNAME:localhost}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS